-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 24, 2025 at 03:59 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tutoring_system`
--

-- --------------------------------------------------------

--
-- Table structure for table `evaluations`
--

CREATE TABLE `evaluations` (
  `id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `evaluator_id` int(11) NOT NULL,
  `evaluatee_id` int(11) NOT NULL,
  `type` enum('mid_term','final','supervisor','teacher','student') NOT NULL,
  `score` decimal(3,1) DEFAULT 0.0,
  `criteria_scores` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`criteria_scores`)),
  `technical_avg` decimal(3,1) DEFAULT 0.0,
  `professional_avg` decimal(3,1) DEFAULT 0.0,
  `comments` text DEFAULT NULL,
  `strengths` text DEFAULT NULL,
  `areas_for_improvement` text DEFAULT NULL,
  `next_steps` text DEFAULT NULL,
  `status` enum('draft','submitted','approved') NOT NULL DEFAULT 'submitted',
  `submission_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `evaluations`
--

INSERT INTO `evaluations` (`id`, `assignment_id`, `evaluator_id`, `evaluatee_id`, `type`, `score`, `criteria_scores`, `technical_avg`, `professional_avg`, `comments`, `strengths`, `areas_for_improvement`, `next_steps`, `status`, `submission_date`, `updated_at`) VALUES
(1, 1, 9, 14, 'mid_term', 2.6, '{\"technical_mastery\":{\"score\":4,\"comment\":\"Utilisation efficace de tous les outils\"},\"work_quality\":{\"score\":2.3,\"comment\":\"Travail de base acceptable\"},\"problem_solving\":{\"score\":3.1,\"comment\":\"Approche m\\u00e9thodique\"},\"documentation\":{\"score\":2.9,\"comment\":\"Documentation correcte\"},\"autonomy\":{\"score\":2.3,\"comment\":\"Demande souvent de l\'aide\"},\"communication\":{\"score\":2.1,\"comment\":\"Informations parfois incompl\\u00e8tes\"},\"team_integration\":{\"score\":2,\"comment\":\"Int\\u00e9gration partielle\"},\"deadline_respect\":{\"score\":2,\"comment\":\"Respect irr\\u00e9gulier des d\\u00e9lais\"}}', 3.1, 2.1, 'L\'étudiant montre une progression satisfaisante. Ses compétences techniques sont en développement et son intégration dans l\'équipe est bonne. Il doit améliorer sa communication et sa documentation.', 'Bonne maîtrise technique, autonomie dans les tâches assignées', 'Documentation du code\nCommunication proactive des problèmes\nParticipation aux réunions', 'Améliorer la documentation\nParticiper plus activement aux réunions d\'équipe', 'submitted', '2023-11-29 23:00:00', '2023-11-29 23:00:00'),
(2, 1, 14, 14, 'student', 3.6, '{\"technical_mastery\":{\"score\":3.7,\"comment\":\"Tr\\u00e8s bonne ma\\u00eetrise technique\"},\"work_quality\":{\"score\":3.4,\"comment\":\"Bonne qualit\\u00e9 de travail\"},\"problem_solving\":{\"score\":4.3,\"comment\":\"Tr\\u00e8s bonne capacit\\u00e9 \\u00e0 r\\u00e9soudre des probl\\u00e8mes\"},\"documentation\":{\"score\":3.2,\"comment\":\"Commentaires utiles\"},\"autonomy\":{\"score\":2.5,\"comment\":\"Travaille seul sur des t\\u00e2ches d\\u00e9finies\"},\"communication\":{\"score\":3.1,\"comment\":\"Expression claire\"},\"team_integration\":{\"score\":3.9,\"comment\":\"Collaboration active\"},\"deadline_respect\":{\"score\":4.1,\"comment\":\"Ponctualit\\u00e9 constante\"}}', 3.7, 3.4, 'Je pense avoir bien progressé dans mon stage. J\'ai acquis de nouvelles compétences techniques et j\'ai pu contribuer à plusieurs projets. Je dois améliorer ma communication avec l\'équipe.', 'Apprentissage rapide des technologies, implication dans les projets', 'Communication plus régulière\nMeilleure organisation du temps', 'Proposer des points d\'avancement hebdomadaires\nTenir un journal des tâches accomplies', 'submitted', '2023-12-02 23:00:00', '2023-12-02 23:00:00'),
(3, 1, 9, 14, 'final', 4.0, '{\"technical_mastery\":{\"score\":4.2,\"comment\":\"Tr\\u00e8s bonne ma\\u00eetrise technique\"},\"work_quality\":{\"score\":4.1,\"comment\":\"Travail soign\\u00e9 et rigoureux\"},\"problem_solving\":{\"score\":3.4,\"comment\":\"Approche m\\u00e9thodique\"},\"documentation\":{\"score\":4,\"comment\":\"Commentaires d\\u00e9taill\\u00e9s\"},\"autonomy\":{\"score\":3.4,\"comment\":\"Demande de l\'aide \\u00e0 bon escient\"},\"communication\":{\"score\":3.5,\"comment\":\"Expression pr\\u00e9cise\"},\"team_integration\":{\"score\":4.6,\"comment\":\"Collaboration exemplaire\"},\"deadline_respect\":{\"score\":5,\"comment\":\"Anticipation des \\u00e9ch\\u00e9ances\"}}', 3.9, 4.1, 'L\'étudiant a réalisé d\'excellents progrès tout au long de son stage. Il a su s\'adapter aux défis techniques et a démontré une bonne capacité d\'intégration dans l\'équipe. Ses compétences techniques se sont nettement améliorées.', 'Maîtrise technique approfondie, autonomie, capacité d\'analyse et résolution de problèmes', 'Communication technique avec les équipes non-techniques\nPrise de recul sur les solutions implémentées', 'Continuer à développer ses compétences en communication\nExplorer des domaines techniques complémentaires', 'submitted', '2024-02-22 23:00:00', '2024-02-22 23:00:00'),
(4, 2, 10, 16, 'mid_term', 2.8, '{\"technical_mastery\":{\"score\":2.1,\"comment\":\"Connaissances de base pr\\u00e9sentes mais limit\\u00e9es\"},\"work_quality\":{\"score\":2.5,\"comment\":\"Bonne qualit\\u00e9 de travail\"},\"problem_solving\":{\"score\":2.5,\"comment\":\"Approche m\\u00e9thodique\"},\"documentation\":{\"score\":2,\"comment\":\"Commentaires basiques\"},\"autonomy\":{\"score\":2.6,\"comment\":\"Travaille seul sur des t\\u00e2ches d\\u00e9finies\"},\"communication\":{\"score\":3.7,\"comment\":\"Tr\\u00e8s bonne communication\"},\"team_integration\":{\"score\":2.7,\"comment\":\"Interactions positives\"},\"deadline_respect\":{\"score\":4,\"comment\":\"Ponctualit\\u00e9 constante\"}}', 2.3, 3.3, 'L\'étudiant montre une progression satisfaisante. Ses compétences techniques sont en développement et son intégration dans l\'équipe est bonne. Il doit améliorer sa communication et sa documentation.', 'Bonne maîtrise technique, autonomie dans les tâches assignées', 'Documentation du code\nCommunication proactive des problèmes\nParticipation aux réunions', 'Améliorer la documentation\nParticiper plus activement aux réunions d\'équipe', 'submitted', '2023-11-29 23:00:00', '2023-11-29 23:00:00'),
(5, 2, 16, 16, 'student', 3.5, '{\"technical_mastery\":{\"score\":4,\"comment\":\"Utilisation efficace de tous les outils\"},\"work_quality\":{\"score\":3,\"comment\":\"Bonne qualit\\u00e9 de travail\"},\"problem_solving\":{\"score\":3.7,\"comment\":\"Tr\\u00e8s bonne capacit\\u00e9 \\u00e0 r\\u00e9soudre des probl\\u00e8mes\"},\"documentation\":{\"score\":4.2,\"comment\":\"Commentaires d\\u00e9taill\\u00e9s\"},\"autonomy\":{\"score\":3.2,\"comment\":\"Demande de l\'aide \\u00e0 bon escient\"},\"communication\":{\"score\":3.3,\"comment\":\"Expression claire\"},\"team_integration\":{\"score\":3.5,\"comment\":\"Collaboration active\"},\"deadline_respect\":{\"score\":3,\"comment\":\"Retards rares\"}}', 3.7, 3.3, 'Je pense avoir bien progressé dans mon stage. J\'ai acquis de nouvelles compétences techniques et j\'ai pu contribuer à plusieurs projets. Je dois améliorer ma communication avec l\'équipe.', 'Apprentissage rapide des technologies, implication dans les projets', 'Communication plus régulière\nMeilleure organisation du temps', 'Proposer des points d\'avancement hebdomadaires\nTenir un journal des tâches accomplies', 'submitted', '2023-12-02 23:00:00', '2023-12-02 23:00:00'),
(6, 2, 10, 16, 'final', 4.2, '{\"technical_mastery\":{\"score\":4.5,\"comment\":\"Expertise technique remarquable\"},\"work_quality\":{\"score\":4,\"comment\":\"Travail soign\\u00e9 et rigoureux\"},\"problem_solving\":{\"score\":3.8,\"comment\":\"Analyse pertinente\"},\"documentation\":{\"score\":4.5,\"comment\":\"Commentaires exhaustifs\"},\"autonomy\":{\"score\":3.1,\"comment\":\"Travaille seul sur des t\\u00e2ches d\\u00e9finies\"},\"communication\":{\"score\":4.3,\"comment\":\"Tr\\u00e8s bonne communication\"},\"team_integration\":{\"score\":4.5,\"comment\":\"Excellente int\\u00e9gration\"},\"deadline_respect\":{\"score\":5,\"comment\":\"Anticipation des \\u00e9ch\\u00e9ances\"}}', 4.2, 4.2, 'L\'étudiant a réalisé d\'excellents progrès tout au long de son stage. Il a su s\'adapter aux défis techniques et a démontré une bonne capacité d\'intégration dans l\'équipe. Ses compétences techniques se sont nettement améliorées.', 'Maîtrise technique approfondie, autonomie, capacité d\'analyse et résolution de problèmes', 'Communication technique avec les équipes non-techniques\nPrise de recul sur les solutions implémentées', 'Continuer à développer ses compétences en communication\nExplorer des domaines techniques complémentaires', 'submitted', '2024-02-22 23:00:00', '2024-02-22 23:00:00'),
(7, 3, 13, 18, 'mid_term', 3.0, '{\"technical_mastery\":{\"score\":2.2,\"comment\":\"Utilisation correcte des outils simples\"},\"work_quality\":{\"score\":3.2,\"comment\":\"Bonne qualit\\u00e9 de travail\"},\"problem_solving\":{\"score\":2.4,\"comment\":\"A besoin d\'aide pour les cas complexes\"},\"documentation\":{\"score\":3.5,\"comment\":\"Tr\\u00e8s bonne documentation\"},\"autonomy\":{\"score\":3.4,\"comment\":\"Demande de l\'aide \\u00e0 bon escient\"},\"communication\":{\"score\":2.5,\"comment\":\"Expression claire\"},\"team_integration\":{\"score\":3.8,\"comment\":\"Tr\\u00e8s bonne int\\u00e9gration\"},\"deadline_respect\":{\"score\":2.7,\"comment\":\"Respect satisfaisant des d\\u00e9lais\"}}', 2.8, 3.1, 'L\'étudiant montre une progression satisfaisante. Ses compétences techniques sont en développement et son intégration dans l\'équipe est bonne. Il doit améliorer sa communication et sa documentation.', 'Bonne maîtrise technique, autonomie dans les tâches assignées', 'Documentation du code\nCommunication proactive des problèmes\nParticipation aux réunions', 'Améliorer la documentation\nParticiper plus activement aux réunions d\'équipe', 'submitted', '2023-11-29 23:00:00', '2023-11-29 23:00:00'),
(8, 3, 18, 18, 'student', 3.3, '{\"technical_mastery\":{\"score\":4.2,\"comment\":\"Utilisation efficace de tous les outils\"},\"work_quality\":{\"score\":2.8,\"comment\":\"Travail conforme aux attentes\"},\"problem_solving\":{\"score\":3.1,\"comment\":\"Bonne capacit\\u00e9 d\'analyse\"},\"documentation\":{\"score\":2.8,\"comment\":\"Commentaires utiles\"},\"autonomy\":{\"score\":3.3,\"comment\":\"Demande de l\'aide \\u00e0 bon escient\"},\"communication\":{\"score\":2.7,\"comment\":\"Partage ad\\u00e9quat d\'informations\"},\"team_integration\":{\"score\":3.5,\"comment\":\"Collaboration active\"},\"deadline_respect\":{\"score\":4.2,\"comment\":\"Tr\\u00e8s bon respect des d\\u00e9lais\"}}', 3.2, 3.4, 'Je pense avoir bien progressé dans mon stage. J\'ai acquis de nouvelles compétences techniques et j\'ai pu contribuer à plusieurs projets. Je dois améliorer ma communication avec l\'équipe.', 'Apprentissage rapide des technologies, implication dans les projets', 'Communication plus régulière\nMeilleure organisation du temps', 'Proposer des points d\'avancement hebdomadaires\nTenir un journal des tâches accomplies', 'submitted', '2023-12-02 23:00:00', '2023-12-02 23:00:00'),
(9, 3, 13, 18, 'final', 3.9, '{\"technical_mastery\":{\"score\":4.2,\"comment\":\"Utilisation efficace de tous les outils\"},\"work_quality\":{\"score\":3.8,\"comment\":\"Livrables pr\\u00e9cis et fiables\"},\"problem_solving\":{\"score\":3.4,\"comment\":\"R\\u00e9sout la plupart des probl\\u00e8mes\"},\"documentation\":{\"score\":5,\"comment\":\"Commentaires exhaustifs\"},\"autonomy\":{\"score\":3,\"comment\":\"Travaille seul sur des t\\u00e2ches d\\u00e9finies\"},\"communication\":{\"score\":4.7,\"comment\":\"Partage optimal des informations\"},\"team_integration\":{\"score\":3.5,\"comment\":\"Tr\\u00e8s bonne int\\u00e9gration\"},\"deadline_respect\":{\"score\":3.6,\"comment\":\"Tr\\u00e8s bon respect des d\\u00e9lais\"}}', 4.1, 3.7, 'L\'étudiant a réalisé d\'excellents progrès tout au long de son stage. Il a su s\'adapter aux défis techniques et a démontré une bonne capacité d\'intégration dans l\'équipe. Ses compétences techniques se sont nettement améliorées.', 'Maîtrise technique approfondie, autonomie, capacité d\'analyse et résolution de problèmes', 'Communication technique avec les équipes non-techniques\nPrise de recul sur les solutions implémentées', 'Continuer à développer ses compétences en communication\nExplorer des domaines techniques complémentaires', 'submitted', '2024-02-22 23:00:00', '2024-02-22 23:00:00'),
(10, 4, 9, 17, 'mid_term', 3.3, '{\"technical_mastery\":{\"score\":3.1,\"comment\":\"Bonne ma\\u00eetrise des technologies principales\"},\"work_quality\":{\"score\":2.2,\"comment\":\"Plusieurs corrections n\\u00e9cessaires\"},\"problem_solving\":{\"score\":3.9,\"comment\":\"Tr\\u00e8s bonne capacit\\u00e9 \\u00e0 r\\u00e9soudre des probl\\u00e8mes\"},\"documentation\":{\"score\":3.7,\"comment\":\"Documentation claire et pr\\u00e9cise\"},\"autonomy\":{\"score\":2.8,\"comment\":\"Demande de l\'aide \\u00e0 bon escient\"},\"communication\":{\"score\":3.6,\"comment\":\"Partage proactif d\'informations\"},\"team_integration\":{\"score\":3.5,\"comment\":\"Appr\\u00e9ci\\u00e9 par l\'\\u00e9quipe\"},\"deadline_respect\":{\"score\":3.6,\"comment\":\"Planification efficace\"}}', 3.2, 3.4, 'L\'étudiant montre une progression satisfaisante. Ses compétences techniques sont en développement et son intégration dans l\'équipe est bonne. Il doit améliorer sa communication et sa documentation.', 'Bonne maîtrise technique, autonomie dans les tâches assignées', 'Documentation du code\nCommunication proactive des problèmes\nParticipation aux réunions', 'Améliorer la documentation\nParticiper plus activement aux réunions d\'équipe', 'submitted', '2023-11-29 23:00:00', '2023-11-29 23:00:00'),
(11, 4, 17, 17, 'student', 3.4, '{\"technical_mastery\":{\"score\":4.3,\"comment\":\"Comp\\u00e9tences techniques avanc\\u00e9es\"},\"work_quality\":{\"score\":3.5,\"comment\":\"Travail soign\\u00e9 et rigoureux\"},\"problem_solving\":{\"score\":2.8,\"comment\":\"Approche m\\u00e9thodique\"},\"documentation\":{\"score\":2.6,\"comment\":\"Commentaires utiles\"},\"autonomy\":{\"score\":3.7,\"comment\":\"Prend des initiatives pertinentes\"},\"communication\":{\"score\":2.7,\"comment\":\"Bonne communication\"},\"team_integration\":{\"score\":3.1,\"comment\":\"Bonne int\\u00e9gration\"},\"deadline_respect\":{\"score\":4,\"comment\":\"Tr\\u00e8s bon respect des d\\u00e9lais\"}}', 3.3, 3.4, 'Je pense avoir bien progressé dans mon stage. J\'ai acquis de nouvelles compétences techniques et j\'ai pu contribuer à plusieurs projets. Je dois améliorer ma communication avec l\'équipe.', 'Apprentissage rapide des technologies, implication dans les projets', 'Communication plus régulière\nMeilleure organisation du temps', 'Proposer des points d\'avancement hebdomadaires\nTenir un journal des tâches accomplies', 'submitted', '2023-12-02 23:00:00', '2023-12-02 23:00:00'),
(12, 4, 9, 17, 'final', 4.1, '{\"technical_mastery\":{\"score\":4.9,\"comment\":\"Ma\\u00eetrise parfaite de l\'environnement technique\"},\"work_quality\":{\"score\":3.1,\"comment\":\"Bonne qualit\\u00e9 de travail\"},\"problem_solving\":{\"score\":4.1,\"comment\":\"Analyse pertinente\"},\"documentation\":{\"score\":3.4,\"comment\":\"Documentation correcte\"},\"autonomy\":{\"score\":5,\"comment\":\"Fait preuve d\'initiative et d\'anticipation\"},\"communication\":{\"score\":4.5,\"comment\":\"Communication excellente\"},\"team_integration\":{\"score\":3,\"comment\":\"Interactions positives\"},\"deadline_respect\":{\"score\":4.7,\"comment\":\"Planification exemplaire\"}}', 3.9, 4.3, 'L\'étudiant a réalisé d\'excellents progrès tout au long de son stage. Il a su s\'adapter aux défis techniques et a démontré une bonne capacité d\'intégration dans l\'équipe. Ses compétences techniques se sont nettement améliorées.', 'Maîtrise technique approfondie, autonomie, capacité d\'analyse et résolution de problèmes', 'Communication technique avec les équipes non-techniques\nPrise de recul sur les solutions implémentées', 'Continuer à développer ses compétences en communication\nExplorer des domaines techniques complémentaires', 'submitted', '2024-02-22 23:00:00', '2024-02-22 23:00:00'),
(13, 5, 11, 124, 'mid_term', 3.3, '{\"technical_mastery\":{\"score\":2.6,\"comment\":\"Utilise correctement les outils du projet\"},\"work_quality\":{\"score\":3.3,\"comment\":\"Bonne qualit\\u00e9 de travail\"},\"problem_solving\":{\"score\":3.4,\"comment\":\"Bonne capacit\\u00e9 d\'analyse\"},\"documentation\":{\"score\":3.4,\"comment\":\"Commentaires utiles\"},\"autonomy\":{\"score\":3.5,\"comment\":\"G\\u00e8re bien son temps de travail\"},\"communication\":{\"score\":4,\"comment\":\"Partage proactif d\'informations\"},\"team_integration\":{\"score\":2.3,\"comment\":\"Collaboration \\u00e0 am\\u00e9liorer\"},\"deadline_respect\":{\"score\":3.8,\"comment\":\"Ponctualit\\u00e9 constante\"}}', 3.2, 3.4, 'L\'étudiant montre une progression satisfaisante. Ses compétences techniques sont en développement et son intégration dans l\'équipe est bonne. Il doit améliorer sa communication et sa documentation.', 'Bonne maîtrise technique, autonomie dans les tâches assignées', 'Documentation du code\nCommunication proactive des problèmes\nParticipation aux réunions', 'Améliorer la documentation\nParticiper plus activement aux réunions d\'équipe', 'submitted', '2023-11-29 23:00:00', '2023-11-29 23:00:00'),
(14, 5, 124, 124, 'student', 3.4, '{\"technical_mastery\":{\"score\":3.9,\"comment\":\"Tr\\u00e8s bonne ma\\u00eetrise technique\"},\"work_quality\":{\"score\":4.5,\"comment\":\"Excellente qualit\\u00e9 de travail\"},\"problem_solving\":{\"score\":3,\"comment\":\"Approche m\\u00e9thodique\"},\"documentation\":{\"score\":2.7,\"comment\":\"Documentation correcte\"},\"autonomy\":{\"score\":2.9,\"comment\":\"Travaille seul sur des t\\u00e2ches d\\u00e9finies\"},\"communication\":{\"score\":3.7,\"comment\":\"Expression pr\\u00e9cise\"},\"team_integration\":{\"score\":2.7,\"comment\":\"Collaboration satisfaisante\"},\"deadline_respect\":{\"score\":3.7,\"comment\":\"Tr\\u00e8s bon respect des d\\u00e9lais\"}}', 3.5, 3.3, 'Je pense avoir bien progressé dans mon stage. J\'ai acquis de nouvelles compétences techniques et j\'ai pu contribuer à plusieurs projets. Je dois améliorer ma communication avec l\'équipe.', 'Apprentissage rapide des technologies, implication dans les projets', 'Communication plus régulière\nMeilleure organisation du temps', 'Proposer des points d\'avancement hebdomadaires\nTenir un journal des tâches accomplies', 'submitted', '2023-12-02 23:00:00', '2023-12-02 23:00:00'),
(15, 5, 11, 124, 'final', 3.8, '{\"technical_mastery\":{\"score\":4.4,\"comment\":\"Utilisation efficace de tous les outils\"},\"work_quality\":{\"score\":3.5,\"comment\":\"Tr\\u00e8s bonne qualit\\u00e9\"},\"problem_solving\":{\"score\":4.5,\"comment\":\"Excellente capacit\\u00e9 d\'analyse et r\\u00e9solution\"},\"documentation\":{\"score\":3.2,\"comment\":\"Commentaires utiles\"},\"autonomy\":{\"score\":4.2,\"comment\":\"G\\u00e8re bien son temps de travail\"},\"communication\":{\"score\":3.2,\"comment\":\"Bonne communication\"},\"team_integration\":{\"score\":3,\"comment\":\"Interactions positives\"},\"deadline_respect\":{\"score\":4.4,\"comment\":\"Ponctualit\\u00e9 constante\"}}', 3.9, 3.7, 'L\'étudiant a réalisé d\'excellents progrès tout au long de son stage. Il a su s\'adapter aux défis techniques et a démontré une bonne capacité d\'intégration dans l\'équipe. Ses compétences techniques se sont nettement améliorées.', 'Maîtrise technique approfondie, autonomie, capacité d\'analyse et résolution de problèmes', 'Communication technique avec les équipes non-techniques\nPrise de recul sur les solutions implémentées', 'Continuer à développer ses compétences en communication\nExplorer des domaines techniques complémentaires', 'submitted', '2024-02-22 23:00:00', '2024-02-22 23:00:00'),
(16, 9, 10, 15, 'mid_term', 2.9, '{\"technical_mastery\":{\"score\":3.6,\"comment\":\"Comp\\u00e9tences techniques avanc\\u00e9es\"},\"work_quality\":{\"score\":2.3,\"comment\":\"Plusieurs corrections n\\u00e9cessaires\"},\"problem_solving\":{\"score\":3.1,\"comment\":\"Approche m\\u00e9thodique\"},\"documentation\":{\"score\":3,\"comment\":\"Documentation fonctionnelle\"},\"autonomy\":{\"score\":2.3,\"comment\":\"Autonomie limit\\u00e9e\"},\"communication\":{\"score\":2.9,\"comment\":\"Expression claire\"},\"team_integration\":{\"score\":3.5,\"comment\":\"Collaboration active\"},\"deadline_respect\":{\"score\":2,\"comment\":\"Planification \\u00e0 am\\u00e9liorer\"}}', 3.0, 2.7, 'L\'étudiant montre une progression satisfaisante. Ses compétences techniques sont en développement et son intégration dans l\'équipe est bonne. Il doit améliorer sa communication et sa documentation.', 'Bonne maîtrise technique, autonomie dans les tâches assignées', 'Documentation du code\nCommunication proactive des problèmes\nParticipation aux réunions', 'Améliorer la documentation\nParticiper plus activement aux réunions d\'équipe', 'submitted', '2023-11-29 23:00:00', '2023-11-29 23:00:00'),
(17, 9, 15, 15, 'student', 3.3, '{\"technical_mastery\":{\"score\":3.7,\"comment\":\"Tr\\u00e8s bonne ma\\u00eetrise technique\"},\"work_quality\":{\"score\":2.9,\"comment\":\"Peu d\'erreurs dans les livrables\"},\"problem_solving\":{\"score\":4.1,\"comment\":\"Analyse pertinente\"},\"documentation\":{\"score\":3.8,\"comment\":\"Tr\\u00e8s bonne documentation\"},\"autonomy\":{\"score\":3.2,\"comment\":\"Demande de l\'aide \\u00e0 bon escient\"},\"communication\":{\"score\":2.7,\"comment\":\"Partage ad\\u00e9quat d\'informations\"},\"team_integration\":{\"score\":3.2,\"comment\":\"Interactions positives\"},\"deadline_respect\":{\"score\":2.7,\"comment\":\"Bonne planification\"}}', 3.6, 3.0, 'Je pense avoir bien progressé dans mon stage. J\'ai acquis de nouvelles compétences techniques et j\'ai pu contribuer à plusieurs projets. Je dois améliorer ma communication avec l\'équipe.', 'Apprentissage rapide des technologies, implication dans les projets', 'Communication plus régulière\nMeilleure organisation du temps', 'Proposer des points d\'avancement hebdomadaires\nTenir un journal des tâches accomplies', 'submitted', '2023-12-02 23:00:00', '2023-12-02 23:00:00'),
(18, 9, 10, 15, 'final', 4.0, '{\"technical_mastery\":{\"score\":4.2,\"comment\":\"Comp\\u00e9tences techniques avanc\\u00e9es\"},\"work_quality\":{\"score\":4.4,\"comment\":\"Travail soign\\u00e9 et rigoureux\"},\"problem_solving\":{\"score\":3.4,\"comment\":\"R\\u00e9sout la plupart des probl\\u00e8mes\"},\"documentation\":{\"score\":4.9,\"comment\":\"Documentation excellente\"},\"autonomy\":{\"score\":3.1,\"comment\":\"Demande de l\'aide \\u00e0 bon escient\"},\"communication\":{\"score\":3.1,\"comment\":\"Partage ad\\u00e9quat d\'informations\"},\"team_integration\":{\"score\":4.8,\"comment\":\"Collaboration exemplaire\"},\"deadline_respect\":{\"score\":3.7,\"comment\":\"Planification efficace\"}}', 4.2, 3.7, 'L\'étudiant a réalisé d\'excellents progrès tout au long de son stage. Il a su s\'adapter aux défis techniques et a démontré une bonne capacité d\'intégration dans l\'équipe. Ses compétences techniques se sont nettement améliorées.', 'Maîtrise technique approfondie, autonomie, capacité d\'analyse et résolution de problèmes', 'Communication technique avec les équipes non-techniques\nPrise de recul sur les solutions implémentées', 'Continuer à développer ses compétences en communication\nExplorer des domaines techniques complémentaires', 'submitted', '2024-02-22 23:00:00', '2024-02-22 23:00:00');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `evaluations`
--
ALTER TABLE `evaluations`
  ADD PRIMARY KEY (`id`),
  ADD KEY `assignment_id` (`assignment_id`),
  ADD KEY `evaluator_id` (`evaluator_id`),
  ADD KEY `evaluatee_id` (`evaluatee_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `evaluations`
--
ALTER TABLE `evaluations`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `evaluations`
--
ALTER TABLE `evaluations`
  ADD CONSTRAINT `evaluations_ibfk_1` FOREIGN KEY (`assignment_id`) REFERENCES `assignments` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `evaluations_ibfk_2` FOREIGN KEY (`evaluator_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `evaluations_ibfk_3` FOREIGN KEY (`evaluatee_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
